spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5433/manage-file

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/drive.file
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret-key: ${JWT_SECRET_KEY}

app:
  encryption:
    password: ${APP_ENCRYPTION_PASSWORD}
    salt: ${APP_ENCRYPTION_SALT}
  frontend:
    origin: http://localhost:3000
    redirect-url: http://localhost:3000/oauth2/callback